### ISSUE TITLE
How to change the size of the cropper ? to make it a square ? 

### ISSUE THREAD

**Issue by Iliyass** [meznaric/react-native-image-cropping#2]
First of all, thanks so much for the module, I have been building my image cropper from scratch for a week or so, but I stuck at getting the correct crop sizes correct, and than I found your module, it's just so easy :smile: 

Well, I really need a way to resize the cropper to be like a square ? 

Thanks again!

**Comment by meznaric** [comment]
Hey @Iliyass I had something like this in my local version of repo already. So I copied it over into this repository. Could you let me know if it works? As I have no quick to verify right now.

Usage instructions:
- Update your dependency version to `0.1.0`
- Use `cropImageWithUrlAndAspect` instead of `cropImageWithUrl`
- Second argument can be any of the following enum types:

``` javascript
 - AspectRatioOriginal
 - AspectRatioSquare
 - AspectRatio3x2
 - AspectRatio5x4
 - AspectRatio4x3
 - AspectRatio5x4
 - AspectRatio7x5
 - AspectRatio16x9
```

Example:

``` javascript
let aspectRatio = ReactNativeImageCropping.AspectRatioSquare;

ReactNativeImageCropping
    .cropImageWithUrlAndAspect(imageUrl, aspectRatio)
    .then(image => {
        //Image is saved in NSTemporaryDirectory!
        //image = {uri, width, height}  
    },
    err => console.log(b));
```
